[book]
authors = ["SovereignAndrey"]
language = "en"
multilingual = false
src = "src"
title = "AST Documentation | Angel Protocol"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/AngelProtocolFinance/ap-documentation"
edit-url-template = "https://github.com/AngelProtocolFinance/ap-documentation/edit/main/{path}"
cname = "docs.angelprotocol.io"
